[package]
name = "ragemp-http"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
reqwest = { version = "0.10.8", features = ["blocking"] }
bytes = "0.6.0"
twox-hash = "1.6.0"
