SLikeNet: Source/include/slikenet/sleep.h File Reference
sleep.h File Reference
#include "Export.h"
Functions
void RAK_DLL_EXPORT RakSleep (unsigned int ms)
Function Documentation
void RAK_DLL_EXPORT RakSleep (unsigned int ms)
Definition at line 41 of file RakSleep.cpp.
References fakeCond, and fakeMutex.
Referenced by SLNet::RNS2_Berkley::BlockOnStopRecvPollingThread(), SLNet::RakPeerInterface::Get64BitUniqueRandomNumber(), SLNet::RakPeer::GetSocket(), SLNet::RakPeer::GetSockets(), ThreadPool< InputType, OutputType >::Pause(), SLNet::RNS2_Berkley::RecvFromLoopInt(), SLNet::RakPeer::Shutdown(), ThreadPool< InputType, OutputType >::StartThreads(), SLNet::RakPeer::Startup(), and ThreadPool< InputType, OutputType >::StopThreads().