/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SLNet {

using System;
using System.Runtime.InteropServices;

public class Cell : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Cell(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Cell obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Cell() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SLikeNetPINVOKE.delete_Cell(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

 	public void Get(out string output)
 	{
 		string temp=new String('c', (int) this.i);
 		output=GetHelper(temp);
 	}
 
  public Cell() : this(SLikeNetPINVOKE.new_Cell__SWIG_0(), true) {
  }

  public void Clear() {
    SLikeNetPINVOKE.Cell_Clear(swigCPtr);
  }

  public void Set(int input) {
    SLikeNetPINVOKE.Cell_Set__SWIG_0(swigCPtr, input);
  }

  public void Set(uint input) {
    SLikeNetPINVOKE.Cell_Set__SWIG_1(swigCPtr, input);
  }

  public void Set(double input) {
    SLikeNetPINVOKE.Cell_Set__SWIG_2(swigCPtr, input);
  }

  public void Set(string input) {
    SLikeNetPINVOKE.Cell_Set__SWIG_3(swigCPtr, input);
  }

  public void Get(out int output) {
    SLikeNetPINVOKE.Cell_Get__SWIG_0(swigCPtr, out output);
  }

  public void Get(out double output) {
    SLikeNetPINVOKE.Cell_Get__SWIG_1(swigCPtr, out output);
  }

  public RakString ToString(Table.ColumnType columnType) {
    RakString ret = new RakString(SLikeNetPINVOKE.Cell_ToString(swigCPtr, (int)columnType), true);
    return ret;
  }

  public Cell CopyData(Cell input) {
    Cell ret = new Cell(SLikeNetPINVOKE.Cell_CopyData(swigCPtr, Cell.getCPtr(input)), false);
    if (SLikeNetPINVOKE.SWIGPendingException.Pending) throw SLikeNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Cell(Cell input) : this(SLikeNetPINVOKE.new_Cell__SWIG_1(Cell.getCPtr(input)), true) {
    if (SLikeNetPINVOKE.SWIGPendingException.Pending) throw SLikeNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public Table.ColumnType EstimateColumnType() {
    Table.ColumnType ret = (Table.ColumnType)SLikeNetPINVOKE.Cell_EstimateColumnType(swigCPtr);
    return ret;
  }

  public bool isEmpty {
    set {
      SLikeNetPINVOKE.Cell_isEmpty_set(swigCPtr, value);
    } 
    get {
      bool ret = SLikeNetPINVOKE.Cell_isEmpty_get(swigCPtr);
      return ret;
    } 
  }

  public double i {
    set {
      SLikeNetPINVOKE.Cell_i_set(swigCPtr, value);
    } 
    get {
      double ret = SLikeNetPINVOKE.Cell_i_get(swigCPtr);
      return ret;
    } 
  }

  public void Set(byte[] inByteArray, int inputLength) {
    SLikeNetPINVOKE.Cell_Set__SWIG_4(swigCPtr, inByteArray, inputLength);
  }

  public void Get(byte[] inOutByteArray, out int outputLength) {
    SLikeNetPINVOKE.Cell_Get__SWIG_2(swigCPtr, inOutByteArray, out outputLength);
  }

  private string GetHelper(string output) {
    string ret = SLikeNetPINVOKE.Cell_GetHelper(swigCPtr, output);
    return ret;
  }

}

}
