[package]
name = "ragemp-raknet"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
reqwest = "0.9.15"
bytes = "0.4.12"
twox-hash = "1.2.0"

[build-dependencies]
cmake = "0.1.38"
bindgen = "0.49"
