var namespace_data_structures =
[
    [ "BinarySearchTree", "db/d19/class_data_structures_1_1_binary_search_tree.xhtml", "db/d19/class_data_structures_1_1_binary_search_tree" ],
    [ "AVLBalancedBinarySearchTree", "dd/d07/class_data_structures_1_1_a_v_l_balanced_binary_search_tree.xhtml", "dd/d07/class_data_structures_1_1_a_v_l_balanced_binary_search_tree" ],
    [ "Page", "da/d80/namespace_data_structures.xhtml#da/da1/struct_data_structures_1_1_page", "da/d80/namespace_data_structures_dup" ],
    [ "BPlusTree", "d7/d58/class_data_structures_1_1_b_plus_tree.xhtml", "d7/d58/class_data_structures_1_1_b_plus_tree" ],
    [ "BytePool", "d4/dca/class_data_structures_1_1_byte_pool.xhtml", "d4/dca/class_data_structures_1_1_byte_pool" ],
    [ "ByteQueue", "d4/dbb/class_data_structures_1_1_byte_queue.xhtml", "d4/dbb/class_data_structures_1_1_byte_queue" ],
    [ "HashIndex", "df/de0/struct_data_structures_1_1_hash_index.xhtml", "df/de0/struct_data_structures_1_1_hash_index" ],
    [ "Hash", "d6/d83/class_data_structures_1_1_hash.xhtml", "d6/d83/class_data_structures_1_1_hash" ],
    [ "Heap", "d1/df3/class_data_structures_1_1_heap.xhtml", "d1/df3/class_data_structures_1_1_heap" ],
    [ "CircularLinkedList", "d3/dbe/class_data_structures_1_1_circular_linked_list.xhtml", "d3/dbe/class_data_structures_1_1_circular_linked_list" ],
    [ "LinkedList", "dd/d55/class_data_structures_1_1_linked_list.xhtml", "dd/d55/class_data_structures_1_1_linked_list" ],
    [ "List", "d4/d78/class_data_structures_1_1_list.xhtml", "d4/d78/class_data_structures_1_1_list" ],
    [ "Map", "dc/da9/class_data_structures_1_1_map.xhtml", "dc/da9/class_data_structures_1_1_map" ],
    [ "MemoryPool", "de/df9/class_data_structures_1_1_memory_pool.xhtml", "de/df9/class_data_structures_1_1_memory_pool" ],
    [ "MLKeyRef", "d3/d76/class_data_structures_1_1_m_l_key_ref.xhtml", "d3/d76/class_data_structures_1_1_m_l_key_ref" ],
    [ "Multilist", "de/d89/class_data_structures_1_1_multilist.xhtml", "de/d89/class_data_structures_1_1_multilist" ],
    [ "OrderedChannelHeap", "de/d25/class_data_structures_1_1_ordered_channel_heap.xhtml", "de/d25/class_data_structures_1_1_ordered_channel_heap" ],
    [ "OrderedList", "da/dfc/class_data_structures_1_1_ordered_list.xhtml", "da/dfc/class_data_structures_1_1_ordered_list" ],
    [ "Queue", "d3/d87/class_data_structures_1_1_queue.xhtml", "d3/d87/class_data_structures_1_1_queue" ],
    [ "QueueLinkedList", "da/d6e/class_data_structures_1_1_queue_linked_list.xhtml", "da/d6e/class_data_structures_1_1_queue_linked_list" ],
    [ "RangeNode", "dd/d2b/struct_data_structures_1_1_range_node.xhtml", "dd/d2b/struct_data_structures_1_1_range_node" ],
    [ "RangeList", "d4/df2/class_data_structures_1_1_range_list.xhtml", "d4/df2/class_data_structures_1_1_range_list" ],
    [ "Table", "d4/de5/class_data_structures_1_1_table.xhtml", "d4/de5/class_data_structures_1_1_table" ],
    [ "ThreadsafeAllocatingQueue", "da/dce/class_data_structures_1_1_threadsafe_allocating_queue.xhtml", "da/dce/class_data_structures_1_1_threadsafe_allocating_queue" ],
    [ "Tree", "de/d2c/class_data_structures_1_1_tree.xhtml", "de/d2c/class_data_structures_1_1_tree" ],
    [ "WeightedGraph", "dd/d9f/class_data_structures_1_1_weighted_graph.xhtml", "dd/d9f/class_data_structures_1_1_weighted_graph" ],
    [ "SingleProducerConsumer", "d0/d72/class_data_structures_1_1_single_producer_consumer.xhtml", "d0/d72/class_data_structures_1_1_single_producer_consumer" ]
];